name: CI Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install invoke
        run: pip install invoke
      - name: install packages
        run: invoke install
      - name: lint
        run: invoke lint
      - name: test
        run: invoke test
      - name: format
        run: invoke design
